<a href="https://colab.research.google.com/github/subhash505/NLP_code/blob/main/1_RNN_Keras.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [ ]:
import numpy as np
from tensorflow.keras.preprocessing.text import one_hot
from tensorflow.keras.preprocessing.sequence import pad_sequences
from tensorflow.keras.models import Sequential
from tensorflow.keras.layers import Dense
from tensorflow.keras.layers import Flatten
from tensorflow.keras.layers import Embedding

reviews = ['nice food',
        'amazing restaurant',
        'too good',
        'just loved it!',
        'will go again',
        'horrible food',
        'never go there',
        'poor service',
        'poor quality',
        'needs improvement']

sentiment = np.array([1,1,1,1,1,0,0,0,0,0])

In [ ]:
one_hot("amazing restaurant",30)

[7, 1]

In [ ]:
reviews.count

<function list.count>

In [ ]:
vocab_size = 30
encoded_reviews = [one_hot(d, vocab_size) for d in reviews]
print(encoded_reviews)

[[10, 3], [7, 1], [8, 11], [19, 25, 25], [12, 26, 25], [5, 3], [25, 26, 24], [27, 10], [27, 11], [1, 24]]


In [ ]:
encoded_reviews[1]

[7, 1]

In [ ]:
max_length = 4
padded_reviews = pad_sequences(encoded_reviews, maxlen=max_length, padding='post')
print(padded_reviews)

[[10  3  0  0]
 [ 7  1  0  0]
 [ 8 11  0  0]
 [19 25 25  0]
 [12 26 25  0]
 [ 5  3  0  0]
 [25 26 24  0]
 [27 10  0  0]
 [27 11  0  0]
 [ 1 24  0  0]]


In [ ]:
embeded_vector_size = 5

model = Sequential()
model.add(Embedding(vocab_size, embeded_vector_size, input_length=max_length,name="embedding"))
model.add(Flatten())
model.add(Dense(1, activation='sigmoid'))

In [ ]:
X = padded_reviews
y = sentiment

In [ ]:
model.compile(optimizer='adam', loss='binary_crossentropy', metrics=['accuracy'])
print(model.summary())

Model: "sequential"
_________________________________________________________________
 Layer (type)                Output Shape              Param #   
 embedding (Embedding)       (None, 4, 5)              150       
                                                                 
 flatten (Flatten)           (None, 20)                0         
                                                                 
 dense (Dense)               (None, 1)                 21        
                                                                 
Total params: 171
Trainable params: 171
Non-trainable params: 0
_________________________________________________________________
None


In [ ]:
model.fit(X, y, epochs=50, verbose=0)

In [ ]:
# evaluate the model
loss, accuracy = model.evaluate(X, y)
accuracy

1/1 [==============================] - 0s 145ms/step - loss: 0.6358 - accuracy: 1.0000


1.0

In [ ]:
weights = model.get_layer('embedding').get_weights()[0]
len(weights)

30

In [ ]:
weights[7]

array([-0.0233159 , -0.06197605, -0.06615529, -0.01750154, -0.05392738],
      dtype=float32)

In [ ]:
weights[10]

array([-0.00367909, -0.00231623,  0.03629979, -0.02260494, -0.07243042],
      dtype=float32)

In [ ]:

weights[16]

array([ 0.01156354, -0.02028729, -0.0041376 ,  0.0476422 , -0.03935443],
      dtype=float32)