<a href="https://colab.research.google.com/github/subhash505/NLP_code/blob/main/Levenshtein_distance_to_calculate_string_similarity.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [2]:
# importing library
import numpy as np

In [3]:
# defining two strings
seq1 = 'text'
seq2 = 'test'

![](https://drive.google.com/uc?export=view&id=1ev-00rhE1Waiy9VbdR2KpO_ML4JnosWj)

In [4]:
# size of matrix
size_x = len(seq1) + 1
size_y = len(seq2) + 1
# creating a matrix with all zeros
matrix = np.zeros((size_x, size_y))

# printing the matrix
matrix

array([[0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0.]])

In [5]:
# filling the first column of the matrix with the index of characters from first string
for x in range(size_x):
    matrix [x, 0] = x
# filling the first row of the matrix with the index of characters from second string
for y in range(size_y):
    matrix [0, y] = y

# printing the matrix
matrix

array([[0., 1., 2., 3., 4.],
       [1., 0., 0., 0., 0.],
       [2., 0., 0., 0., 0.],
       [3., 0., 0., 0., 0.],
       [4., 0., 0., 0., 0.]])

In [6]:
# for each column
for x in range(1, size_x):
    # for each row
    for y in range(1, size_y):
        # check if the characters are same
        if seq1[x-1] == seq2[y-1]:
            # fill the element with the minimum of (diagonal value, first corresponding value + 1, second corresponding value + 1) 
            matrix [x,y] = min(
                matrix[x-1, y-1],
                matrix[x-1, y] + 1,                    
                matrix[x, y-1] + 1
            )
        # if characters are not same
        else:
            # fill the element with the minimum of corresponding values + 1
            matrix [x,y] = min(
                matrix[x-1,y] + 1,
                matrix[x-1,y-1] + 1,
                matrix[x,y-1] + 1
            )

# final matrix
matrix

array([[0., 1., 2., 3., 4.],
       [1., 0., 1., 2., 3.],
       [2., 1., 0., 1., 2.],
       [3., 2., 1., 1., 2.],
       [4., 3., 2., 2., 1.]])

In [7]:
# levenshtein distance
matrix[size_x - 1, size_y - 1]

1.0

In [8]:
# defining the function to calculate levenshtein distance between two strings
def levenshtein_distance(seq1, seq2):

    # size of matrix
    size_x = len(seq1) + 1
    size_y = len(seq2) + 1
    # creating a matrix with all zeros
    matrix = np.zeros((size_x, size_y))

    # filling the first column of the matrix with the index of characters from first string
    for x in range(size_x):
        matrix [x, 0] = x
    # filling the first row of the matrix with the index of characters from second string
    for y in range(size_y):
        matrix [0, y] = y

    # for each column
    for x in range(1, size_x):
        # for each row
        for y in range(1, size_y):
            # check if the characters are same
            if seq1[x-1] == seq2[y-1]:
                # fill the element with the minimum of (diagonal value, first corresponding value + 1, second corresponding value + 1) 
                matrix [x,y] = min(
                    matrix[x-1, y-1],
                    matrix[x-1, y] + 1,                    
                    matrix[x, y-1] + 1
                )
            # if characters are not same
            else:
                # fill the element with the minimum of corresponding values + 1
                matrix [x,y] = min(
                    matrix[x-1,y] + 1,
                    matrix[x-1,y-1] + 1,
                    matrix[x,y-1] + 1
                )

    # printing the final matrix            
    print (matrix)
    
    # returning the levenshtein distance
    return (matrix[size_x - 1, size_y - 1])

In [19]:
# defining two sequences
seq1 = 'Recognition'
seq2 = 'Radiopticon'

In [20]:
levenshtein_distance(seq1, seq2)

[[ 0.  1.  2.  3.  4.  5.  6.  7.  8.  9. 10. 11.]
 [ 1.  0.  1.  2.  3.  4.  5.  6.  7.  8.  9. 10.]
 [ 2.  1.  1.  2.  3.  4.  5.  6.  7.  8.  9. 10.]
 [ 3.  2.  2.  2.  3.  4.  5.  6.  7.  7.  8.  9.]
 [ 4.  3.  3.  3.  3.  3.  4.  5.  6.  7.  7.  8.]
 [ 5.  4.  4.  4.  4.  4.  4.  5.  6.  7.  8.  8.]
 [ 6.  5.  5.  5.  5.  5.  5.  5.  6.  7.  8.  8.]
 [ 7.  6.  6.  6.  5.  6.  6.  6.  5.  6.  7.  8.]
 [ 8.  7.  7.  7.  6.  6.  7.  6.  6.  6.  7.  8.]
 [ 9.  8.  8.  8.  7.  7.  7.  7.  6.  7.  7.  8.]
 [10.  9.  9.  9.  8.  7.  8.  8.  7.  7.  7.  8.]
 [11. 10. 10. 10.  9.  8.  8.  9.  8.  8.  8.  7.]]


7.0

In [12]:
! pip install tkinter

Looking in indexes: https://pypi.org/simple, https://us-python.pkg.dev/colab-wheels/public/simple/
ERROR: Could not find a version that satisfies the requirement tkinter (from versions: none)
ERROR: No matching distribution found for tkinter


In [18]:

#@title
import tkinter as tk
from tkinter.constants import *

ROWS, COLS = 2, 2

def process(entry_widgets, row, col):
    var_name = entry_widgets[row][col].cget('textvariable')
    var = root.variables[var_name]
    try:
        value = float(var.get())
    except ValueError:  # Something invalid (or nothing) was entered.
        value = 0
    var.set(value+5)  # Update value.


root = tk.Tk()

# Create a grid of Entry widgets.
entries = []
root.variables = {}  # To track StringVars.

for x in range(COLS):
    row = []
    for y in range(ROWS):
        var = tk.StringVar(master=root)  # Create variable.
        root.variables[str(var)] = var  # Track them by name.
        entry = tk.Entry(root, textvariable=var)
        entry.grid(row=x, column=y)
        row.append(entry)
    entries.append(row)


btn = tk.Button(root, text='Process', command=lambda: process(entries, 0, 1))
btn.grid(row=2, column=0, columnspan=COLS, sticky=E+W)

root.mainloop()

TclError: ignored